from consts import SECRET_KEY, DEBUG, PREFERRED_URL_SCHEME, WEBSERVER_NAME, APPLICATION_ROOT, MAX_CONTENT_LENGTH

SECRET_KEY = SECRET_KEY
DEBUG = DEBUG
PREFERRED_URL_SCHEME = PREFERRED_URL_SCHEME
SERVER_NAME = WEBSERVER_NAME
APPLICATION_ROOT = APPLICATION_ROOT
MAX_CONTENT_LENGTH = MAX_CONTENT_LENGTH
